name: Publish

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v2

            - name: Setup node environment
              uses: actions/setup-node@v1.4.2
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/

            - name: Download cache
              uses: actions/cache@v2.0.0
              with:
                  key: cds-routing-handlers
                  path: node_modules/*

            - name: Install & Build
              run: |
                  yarn install
                  yarn build

            - name: Upload a build artifact
              uses: actions/upload-artifact@v2
              with:
                  name: cds-routing-handlers-artifacts
                  path: lib/*

    publish:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v2

            - name: Download a Build Artifact
              uses: actions/download-artifact@v2
              with:
                  name: cds-routing-handlers-artifacts
                  path: lib/*

            - name: Setup node environment
              uses: actions/setup-node@v1.4.2
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/

            - name: Publish to npm
              run: npm publish --access public
              env:
                  NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
